name: CI - Build 

on:
  push: 
    branches:
      - "main"

# It'll be tempting to use GitHub Actions matrix strategies to make jobs per OS/output file format,
# but don't. 
# Different output formats and file names and so on - gotta be handled with care, manually.
# Lots of jobs to run here!
jobs:

  # This job is purely for sanity-checking/testing.
  # If the build fails here, no point attempting to make platform installers. 
  build-react:
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # Could maybe even run a test suite here, lol
      # - name: Test the ReactJS app 
      #   run: npm run react:test

      # Build the project
      - name: Build the ReactJS app
        run: npm run react:build

      

  build-android:
    needs: [build-react]
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # Set up the Android workspace
      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      # Refresh Android project icons & other visual assets
      - name: Android icon/splash/etc asset refresh
        run: npm run capacitor:android:prepare:assets

      # Sync the ReactJS app build into the Android project
      - name: React->Android Sync 
        run: npx cap sync 

      # Build the Android app bundle (.AAB file)
      - name: Confirm permissions on the Android build file
        run: chmod +x ./android/gradlew
      - name: Build the AAB file
        run: cd android && ./gradlew bundle

      # Confirm what type of build outputs we got by recursively logging through the big output mess
      - name: Log build output files
        run: ls -R ./android/app/build/outputs/

      # Get Android app signing keys involved 
      - name: Pull signing key from org secrets 
        run: |
          echo "${{secrets.GOOGLEPLAY_SIGNINGKEYBASE64}}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks
      # - name: Sign the built bundle 
      #   run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.GOOGLEPLAY_KEYSTOREPASS }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release
      - name: Sign the built Android app bundle 
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: ./android/app/build/outputs/bundle/release/
          signingKey: ${{ secrets.GOOGLEPLAY_SIGNINGKEYBASE64}}
          keyAlias: ${{ secrets.GOOGLEPLAY_KEYALIAS }}
          keyStorePassword: ${{ secrets.GOOGLEPLAY_KEYSTOREPASS }}
          keyPassword: ${{ secrets.GOOGLEPLAY_KEYSTOREKEYPASS }}
          buildToolsVersion: 36.0.0

      # Rename the signed output file so it has the app name in it
      # It's not a huge deal - users shouldn't be grabbing AAB file directly,
      # they get used by Google Play Store to become what users download,
      # but it's always sad to see "app-release-signed.aab" in 
      # the artifact ZIPs when troubleshooting this stuff.
      - name: Rename the signed release output file
        id: release_rename
        run: |
          mv ${{ steps.sign_app.outputs.signedFile }} ./YourAppName.aab
          renamed_output=./YourAppName.aab
          echo "renamed_output=$renamed_output" >> "$GITHUB_OUTPUT"
          echo "file_name=$(basename "${renamed_output}")" >> "$GITHUB_OUTPUT"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.release_rename.outputs.file_name }}
          path: ${{ steps.release_rename.outputs.renamed_output }}
          retention-days: 30

  build-windows-installer:
    needs: [build-react]
    runs-on: ubuntu-latest
    container: electronuserland/builder:wine
    steps:
      # Fix for Wine permissions in GitHub Actions job runner environments
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"

      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the Windows installer 
        run: npm run electron:build:windows:installer

      - name: Confirming that the build output exists in the expected place
        id: output_finder
        run: |
          file_path=$(find . -name '*-Setup.exe' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.output_finder.outputs.file_name }}
          path: |
            ${{ steps.output_finder.outputs.file_path }}
          retention-days: 30

  build-windows-portable:
    needs: [build-react]
    runs-on: ubuntu-latest
    container: electronuserland/builder:wine
    steps:

      # Fix for Wine permissions in GitHub Actions job runner environments
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"

      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the Windows portable executable 
        run: npm run electron:build:windows:portable

      - name: Confirming that the build output exists in the expected place
        id: output_finder
        run: |
          file_path=$(find . -name '*-Portable.exe' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.output_finder.outputs.file_name }}
          path: |
            ${{ steps.output_finder.outputs.file_path }}
          retention-days: 30

  build-linux-deb:
    needs: [build-react]
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the DEB installer 
        run: npm run electron:build:linux:deb

      - name: Confirming that the build output exists in the expected place
        id: output_finder
        run: |
          file_path=$(find . -name '*.deb' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"
          cat "$GITHUB_OUTPUT"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.output_finder.outputs.file_name }}
          path: |
            ${{ steps.output_finder.outputs.file_path }}
          retention-days: 30

  build-macos-dmg:
    needs: [build-react]
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the Windows installer 
        run: npm run electron:build:macos:dmg

      - name: Confirming that the build output exists in the expected place
        run: | 
          echo TODO!

        # ls -IR release/

      # Upload signed release as artifact
      # - name: Upload release bundle 
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: ${{ steps.output_finder.outputs.file_name }}
      #     path: |
      #       ${{ steps.output_finder.outputs.file_path }}
      #     retention-days: 30


  alert-discord:
    needs: [build-android, build-windows-installer, build-windows-portable, build-linux-deb, build-macos-dmg]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/download-artifact@v8
        id: download-step
        with:
          path: builds-storage
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R builds-storage
      - name: Check if download-artifact outputs is anything useful
        run: echo ${{ steps.download-step.outputs.download-path }}
      - name: Discord Webhook Action
        uses: MineBartekSA/discord-webhook@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          attachment: |
            - file: ^builds-storage\/YourAppName-Linux-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?.deb
            - file: ^builds-storage\/YourAppName.aab
            - file: ^builds-storage\/YourAppName-Windows-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?-Portable.exe
            - file: ^builds-storage\/YourAppName-Windows-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?-Setup.exe
      
  # Trigger some other workflow or job once all the build jobs above are finished
  # e.g. attach all builds to a release, or push some builds to app stores, or both, blah blah blah