name: Purge All GitHub Actions Artifacts
# Manually dispatch this workflow to clean out old builds
# and reduce GitHub Actions storage usage.
on:
  workflow_dispatch: {}


jobs:
  purge_all_artifacts:
    name: Purge All Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Purge all workflow run artifacts
        id: artifact_purge
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts